name = "Theseus Services"
prefix = "tacs"
author = "Theseus Services Team"
files = [
    "mod.cpp",
    "README.md",
    "AUTHORS.txt",
    "LICENSE",
    "logo_tacs_ca.paa",
    "logo_tacs_small_ca.paa",
    "meta.cpp"
]

modname = "theseus_services"
key_name = "{{prefix}}_{{version}}"
authority = "{{prefix}}_{{version}}"

releasebuild = [
    "@zip TheseusServices_{{version}}"
]

[header_exts]
version = "{{git \"id 8\"}}"
