name = "Theseus Services"
prefix = "tacs"
author = "Theseus Incorporated"

[files]
include = [
    "mod.cpp",
    "README.md",
    "AUTHORS.txt",
    "LICENSE",
    "logo_tacs_ca.paa",
    "logo_tacs_small_ca.paa",
    "meta.cpp"
]

[version]
git_hash = 0

[hemtt.config]
preset = "Hemtt"

[hemtt.release]
folder = "theseus_services"
